import * as fs from 'fs';

const newWords = [
  {
    id: "w_b7_313",
    word: "Corporate",
    ipa: "/ˈkɔː.pər.ət/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Relating to a large company or group.",
    vietnameseDefinition: "Thuộc về công ty, đoàn thể",
    collocations: ["corporate culture", "corporate identity", "corporate responsibility"],
    example: "The company has a strong corporate culture that values innovation.",
    vietnameseExample: "Công ty có một văn hóa doanh nghiệp mạnh mẽ coi trọng sự đổi mới.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_314",
    word: "Correlation",
    ipa: "/ˌkɒr.əˈleɪ.ʃən/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A connection or relationship between two or more facts, numbers, etc.",
    vietnameseDefinition: "Sự tương quan",
    collocations: ["strong correlation", "direct correlation", "show a correlation"],
    example: "There's a high correlation between smoking and lung cancer.",
    vietnameseExample: "Có một sự tương quan cao giữa việc hút thuốc và ung thư phổi.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_315",
    word: "Correspond",
    ipa: "/ˌkɒr.ɪˈspɒnd/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To match or be similar or equal.",
    vietnameseDefinition: "Tương ứng, phù hợp",
    collocations: ["correspond closely", "correspond exactly", "correspond to"],
    example: "The written record does not correspond to what was actually said.",
    vietnameseExample: "Bản ghi chép không tương ứng với những gì thực sự được nói.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_316",
    word: "Criteria",
    ipa: "/kraɪˈtɪə.ri.ə/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A standard by which you judge, decide about, or deal with something.",
    vietnameseDefinition: "Tiêu chí",
    collocations: ["meet the criteria", "strict criteria", "selection criteria"],
    example: "The health service should not be judged by financial criteria alone.",
    vietnameseExample: "Dịch vụ y tế không nên chỉ được đánh giá bằng các tiêu chí tài chính.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_317",
    word: "Crucial",
    ipa: "/ˈkruː.ʃəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Extremely important or necessary.",
    vietnameseDefinition: "Quan trọng, cốt yếu",
    collocations: ["crucial role", "crucial factor", "crucial importance"],
    example: "Her work has been crucial to the project's success.",
    vietnameseExample: "Công việc của cô ấy đóng vai trò cốt yếu đối với thành công của dự án.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_318",
    word: "Cultivate",
    ipa: "/ˈkʌl.tɪ.veɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To try to develop and improve something.",
    vietnameseDefinition: "Trau dồi, nuôi dưỡng",
    collocations: ["cultivate a relationship", "cultivate an image", "cultivate skills"],
    example: "She has cultivated an image as a tough negotiator.",
    vietnameseExample: "Cô ấy đã xây dựng hình ảnh như một nhà đàm phán cứng rắn.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_319",
    word: "Currency",
    ipa: "/ˈkʌr.ən.si/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The money that is used in a particular country at a particular time.",
    vietnameseDefinition: "Tiền tệ",
    collocations: ["foreign currency", "hard currency", "local currency"],
    example: "The local currency is the Swiss franc.",
    vietnameseExample: "Đồng tiền địa phương là đồng franc Thụy Sĩ.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_320",
    word: "Cycle",
    ipa: "/ˈsaɪ.kəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A group of events that happen in a particular order, one following the other, and are often repeated.",
    vietnameseDefinition: "Chu kỳ",
    collocations: ["vicious cycle", "life cycle", "economic cycle"],
    example: "The economy follows a cycle of boom and bust.",
    vietnameseExample: "Nền kinh tế tuân theo một chu kỳ bùng nổ và suy thoái.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_321",
    word: "Debate",
    ipa: "/dɪˈbeɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Serious discussion of a subject in which many people take part.",
    vietnameseDefinition: "Cuộc tranh luận",
    collocations: ["heated debate", "public debate", "spark a debate"],
    example: "Education is the current focus of public debate.",
    vietnameseExample: "Giáo dục là trọng tâm hiện tại của cuộc tranh luận công khai.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_322",
    word: "Decade",
    ipa: "/ˈdek.eɪd/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A period of ten years, especially a period such as 2010 to 2019.",
    vietnameseDefinition: "Thập kỷ",
    collocations: ["past decade", "next decade", "several decades"],
    example: "Environmental awareness has increased dramatically over the past decade.",
    vietnameseExample: "Nhận thức về môi trường đã tăng lên đáng kể trong thập kỷ qua.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_323",
    word: "Decline",
    ipa: "/dɪˈklaɪn/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To gradually become less, worse, or lower.",
    vietnameseDefinition: "Sự suy giảm, từ chối",
    collocations: ["sharp decline", "steady decline", "decline an offer"],
    example: "His interest in the project declined after his wife died.",
    vietnameseExample: "Sự quan tâm của anh ấy đối với dự án đã giảm sút sau khi vợ anh ấy qua đời.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_324",
    word: "Deduce",
    ipa: "/dɪˈdʒuːs/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To reach an answer or a decision by thinking carefully about the known facts.",
    vietnameseDefinition: "Suy luận",
    collocations: ["deduce from", "logically deduce", "deduce a conclusion"],
    example: "We cannot deduce very much from these figures.",
    vietnameseExample: "Chúng ta không thể suy luận được nhiều từ những con số này.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_325",
    word: "Define",
    ipa: "/dɪˈfaɪn/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To say exactly what something means, or what someone or something is like.",
    vietnameseDefinition: "Định nghĩa, xác định",
    collocations: ["clearly define", "strictly define", "define a role"],
    example: "It is very difficult to define the concept of beauty.",
    vietnameseExample: "Rất khó để định nghĩa khái niệm về cái đẹp.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_326",
    word: "Definite",
    ipa: "/ˈdef.ɪ.nət/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Fixed, certain, or clear.",
    vietnameseDefinition: "Rõ ràng, chắc chắn",
    collocations: ["definite answer", "definite proof", "definite plan"],
    example: "We need a definite answer by tomorrow.",
    vietnameseExample: "Chúng tôi cần một câu trả lời chắc chắn vào ngày mai.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_327",
    word: "Demonstrate",
    ipa: "/ˈdem.ən.streɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To show or make make something clear.",
    vietnameseDefinition: "Chứng minh, thể hiện",
    collocations: ["clearly demonstrate", "demonstrate an ability", "demonstrate a commitment"],
    example: "These numbers clearly demonstrate the size of the economic problem facing the country.",
    vietnameseExample: "Những con số này chứng minh rõ ràng quy mô của vấn đề kinh tế mà đất nước đang phải đối mặt.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_328",
    word: "Denote",
    ipa: "/dɪˈnəʊt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To represent something.",
    vietnameseDefinition: "Biểu thị, chỉ rõ",
    collocations: ["denote a change", "clearly denote", "denote meaning"],
    example: "The colour red is used to denote passion or danger.",
    vietnameseExample: "Màu đỏ được sử dụng để biểu thị niềm đam mê hoặc sự nguy hiểm.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_329",
    word: "Deny",
    ipa: "/dɪˈnaɪ/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To say that something is not true.",
    vietnameseDefinition: "Phủ nhận",
    collocations: ["strongly deny", "categorically deny", "deny an allegation"],
    example: "He completely denied the allegations against him.",
    vietnameseExample: "Anh ta hoàn toàn phủ nhận các cáo buộc chống lại mình.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_330",
    word: "Depress",
    ipa: "/dɪˈpres/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To cause someone to feel unhappy and without hope.",
    vietnameseDefinition: "Làm chán nản, làm suy yếu",
    collocations: ["deeply depress", "depress the market", "depress prices"],
    example: "This weather depresses me.",
    vietnameseExample: "Thời tiết này làm tôi chán nản.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_331",
    word: "Derive",
    ipa: "/dɪˈraɪv/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To get something from something else.",
    vietnameseDefinition: "Bắt nguồn từ, nhận được từ",
    collocations: ["derive from", "derive pleasure", "derive benefit"],
    example: "Many people derive their self-worth from their work.",
    vietnameseExample: "Nhiều người nhận được giá trị bản thân từ công việc của họ.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_332",
    word: "Design",
    ipa: "/dɪˈzaɪn/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To make or draw plans for something, for example clothes or buildings.",
    vietnameseDefinition: "Thiết kế",
    collocations: ["interior design", "graphic design", "design a system"],
    example: "He studied art and design at university.",
    vietnameseExample: "Anh ấy đã học nghệ thuật và thiết kế ở trường đại học.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_333",
    word: "Despite",
    ipa: "/dɪˈspaɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Without taking any notice of or being influenced by; not prevented by.",
    vietnameseDefinition: "Mặc dù",
    collocations: ["despite the fact that", "despite efforts", "despite warnings"],
    example: "I still enjoyed the week despite the weather.",
    vietnameseExample: "Tôi vẫn tận hưởng tuần lễ mặc dù thời tiết xấu.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_334",
    word: "Detect",
    ipa: "/dɪˈtekt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To notice something that is partly hidden or not clear, or to discover something.",
    vietnameseDefinition: "Phát hiện",
    collocations: ["early detect", "detect a change", "detect a pattern"],
    example: "Some sounds cannot be detected by the human ear.",
    vietnameseExample: "Một số âm thanh không thể được phát hiện bởi tai người.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_335",
    word: "Deviate",
    ipa: "/ˈdiː.vi.eɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To do something that is different from the usual or common way of behaving.",
    vietnameseDefinition: "Lệch hướng, sai lệch",
    collocations: ["deviate from", "significantly deviate", "deviate from the norm"],
    example: "The recent pattern of weather deviates from the norm for this time of year.",
    vietnameseExample: "Kiểu thời tiết gần đây sai lệch so với mức bình thường vào thời điểm này trong năm.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_336",
    word: "Device",
    ipa: "/dɪˈvaɪs/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An object or machine that has been invented for a particular purpose.",
    vietnameseDefinition: "Thiết bị",
    collocations: ["electronic device", "mobile device", "medical device"],
    example: "A mouse is a device which makes it easier to use a computer.",
    vietnameseExample: "Chuột là một thiết bị giúp sử dụng máy tính dễ dàng hơn.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_337",
    word: "Devote",
    ipa: "/dɪˈvəʊt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To give all of something, especially your time, effort, or love, or yourself, to something you believe in or to a person.",
    vietnameseDefinition: "Cống hiến, dành hết cho",
    collocations: ["devote time", "devote energy", "devote oneself to"],
    example: "He left the Senate to devote more time to his family.",
    vietnameseExample: "Ông rời Thượng viện để dành nhiều thời gian hơn cho gia đình.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_338",
    word: "Differentiate",
    ipa: "/ˌdɪf.əˈren.ʃi.eɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To show or find the difference between things that are compared.",
    vietnameseDefinition: "Phân biệt",
    collocations: ["differentiate between", "clearly differentiate", "differentiate a product"],
    example: "We do not differentiate between our employees on the basis of their race, religion, or national origin.",
    vietnameseExample: "Chúng tôi không phân biệt đối xử giữa các nhân viên dựa trên chủng tộc, tôn giáo hoặc nguồn gốc quốc gia của họ.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_339",
    word: "Dimension",
    ipa: "/ˌdaɪˈmen.ʃən/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A measurement of something in a particular direction, especially its height, length, or width.",
    vietnameseDefinition: "Kích thước, khía cạnh",
    collocations: ["new dimension", "add a dimension", "political dimension"],
    example: "Please specify the dimensions of the room.",
    vietnameseExample: "Vui lòng chỉ định kích thước của căn phòng.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_340",
    word: "Diminish",
    ipa: "/dɪˈmɪn.ɪʃ/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To reduce or be reduced in size or importance.",
    vietnameseDefinition: "Giảm bớt, thu nhỏ",
    collocations: ["diminish the impact", "gradually diminish", "diminish in value"],
    example: "I don't want to diminish her achievements, but she did have a lot of help.",
    vietnameseExample: "Tôi không muốn làm giảm đi những thành tựu của cô ấy, nhưng cô ấy đã có rất nhiều sự giúp đỡ.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_341",
    word: "Discrete",
    ipa: "/dɪˈskriːt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Having an independent physical form or identity.",
    vietnameseDefinition: "Riêng biệt, rời rạc",
    collocations: ["discrete units", "discrete categories", "discrete steps"],
    example: "These small companies now have their own discrete identity.",
    vietnameseExample: "Những công ty nhỏ này hiện có bản sắc riêng biệt của họ.",
    level: "C2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_342",
    word: "Discriminate",
    ipa: "/dɪˈskrɪm.ɪ.neɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To treat a person or particular group of people differently, especially in a worse way from the way in which you treat other people, because of their skin colour, sex, sexuality, etc.",
    vietnameseDefinition: "Phân biệt đối xử",
    collocations: ["discriminate against", "discriminate on the basis of", "unlawfully discriminate"],
    example: "She felt she had been discriminated against because of her age.",
    vietnameseExample: "Cô cảm thấy mình bị phân biệt đối xử vì tuổi tác.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_343",
    word: "Displace",
    ipa: "/dɪˈspleɪs/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To force something or someone out of its usual or original position.",
    vietnameseDefinition: "Thay thế, dời chỗ",
    collocations: ["displace workers", "be displaced by", "displace populations"],
    example: "The building of a new dam will displace thousands of people who live in this area.",
    vietnameseExample: "Việc xây dựng một con đập mới sẽ dời chỗ hàng ngàn người sống trong khu vực này.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_344",
    word: "Display",
    ipa: "/dɪˈspleɪ/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To arrange something or a collection of things so that it can be seen by the public.",
    vietnameseDefinition: "Trưng bày, hiển thị",
    collocations: ["on display", "public display", "display a sign"],
    example: "Family photographs were displayed on the wall.",
    vietnameseExample: "Những bức ảnh gia đình được trưng bày trên tường.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_345",
    word: "Dispose",
    ipa: "/dɪˈspəʊz/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To get rid of someone or something or deal with something so that the matter is finished.",
    vietnameseDefinition: "Vứt bỏ, giải quyết",
    collocations: ["dispose of", "safely dispose", "properly dispose"],
    example: "How did they dispose of the body?",
    vietnameseExample: "Họ đã vứt bỏ cái xác như thế nào?",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_346",
    word: "Distinct",
    ipa: "/dɪˈstɪŋkt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Clearly noticeable; that certainly exists.",
    vietnameseDefinition: "Khác biệt, rõ ràng",
    collocations: ["distinct advantage", "distinct possibility", "distinct from"],
    example: "There's a distinct smell of cigarettes in here.",
    vietnameseExample: "Có một mùi thuốc lá rõ rệt ở đây.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_347",
    word: "Distort",
    ipa: "/dɪˈstɔːt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To change something from its usual, original, natural, or intended meaning, condition, or shape.",
    vietnameseDefinition: "Xuyên tạc, bóp méo",
    collocations: ["distort the truth", "distort reality", "distort competition"],
    example: "The map distorted the size of the countries.",
    vietnameseExample: "Bản đồ đã làm bóp méo kích thước của các quốc gia.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_348",
    word: "Distribute",
    ipa: "/dɪˈstrɪb.juːt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To give something out to several people, or to spread or supply something.",
    vietnameseDefinition: "Phân phối",
    collocations: ["widely distribute", "distribute evenly", "distribute wealth"],
    example: "The books will be distributed free to local schools.",
    vietnameseExample: "Sách sẽ được phân phối miễn phí cho các trường học địa phương.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_349",
    word: "Diverse",
    ipa: "/daɪˈvɜːs/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Including many different types of people or things.",
    vietnameseDefinition: "Đa dạng",
    collocations: ["diverse range", "diverse background", "culturally diverse"],
    example: "New York is a very culturally diverse city.",
    vietnameseExample: "New York là một thành phố rất đa dạng về văn hóa.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_350",
    word: "Document",
    ipa: "/ˈdɒk.jə.mənt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A paper or set of papers with written or printed information, especially of an official type.",
    vietnameseDefinition: "Tài liệu",
    collocations: ["official document", "legal document", "sign a document"],
    example: "They are charged with using forged documents.",
    vietnameseExample: "Họ bị buộc tội sử dụng tài liệu giả mạo.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_351",
    word: "Domain",
    ipa: "/dəˈmeɪn/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An area of interest or an area over which a person has control.",
    vietnameseDefinition: "Lĩnh vực, phạm vi",
    collocations: ["public domain", "domain name", "within the domain of"],
    example: "She treated the business as her private domain.",
    vietnameseExample: "Cô ấy coi công việc kinh doanh như lĩnh vực riêng của mình.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_352",
    word: "Domestic",
    ipa: "/dəˈmes.tɪk/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Relating to a person's own country.",
    vietnameseDefinition: "Trong nước, nội địa",
    collocations: ["domestic market", "domestic flight", "domestic violence"],
    example: "Domestic flights go from Terminal 1.",
    vietnameseExample: "Các chuyến bay nội địa khởi hành từ Nhà ga 1.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_353",
    word: "Dominate",
    ipa: "/ˈdɒm.ɪ.neɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To have control over a place or person.",
    vietnameseDefinition: "Thống trị, chi phối",
    collocations: ["dominate the market", "dominate the conversation", "male-dominated"],
    example: "He refuses to let others speak and dominates every meeting.",
    vietnameseExample: "Anh ta từ chối để người khác nói và chi phối mọi cuộc họp.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_354",
    word: "Draft",
    ipa: "/drɑːft/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A piece of text, a formal suggestion, or a drawing in its original state, often containing the main ideas and intentions but not the developed form.",
    vietnameseDefinition: "Bản nháp",
    collocations: ["first draft", "rough draft", "final draft"],
    example: "This is only a rough draft - the finished article will have pictures too.",
    vietnameseExample: "Đây chỉ là bản nháp thô - bài viết hoàn chỉnh sẽ có cả hình ảnh.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_355",
    word: "Drama",
    ipa: "/ˈdrɑː.mə/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A play in a theatre or on television or radio, or plays and acting generally.",
    vietnameseDefinition: "Kịch, phim truyền hình",
    collocations: ["costume drama", "historical drama", "human drama"],
    example: "She's been in several television dramas.",
    vietnameseExample: "Cô ấy đã tham gia một số bộ phim truyền hình.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_356",
    word: "Duration",
    ipa: "/djʊəˈreɪ.ʃən/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The length of time that something lasts.",
    vietnameseDefinition: "Khoảng thời gian",
    collocations: ["for the duration", "duration of the flight", "short duration"],
    example: "He planned a stay of two years' duration.",
    vietnameseExample: "Anh ấy đã lên kế hoạch cho một kỳ nghỉ kéo dài hai năm.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_357",
    word: "Dynamic",
    ipa: "/daɪˈnæm.ɪk/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Having a lot of ideas and enthusiasm.",
    vietnameseDefinition: "Năng động",
    collocations: ["dynamic personality", "dynamic environment", "group dynamics"],
    example: "She's young and dynamic and will be a great addition to the team.",
    vietnameseExample: "Cô ấy trẻ trung, năng động và sẽ là một sự bổ sung tuyệt vời cho đội.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_358",
    word: "Economy",
    ipa: "/iˈkɒn.ə.mi/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The system of trade and industry by which the wealth of a country is made and used.",
    vietnameseDefinition: "Nền kinh tế",
    collocations: ["global economy", "market economy", "boost the economy"],
    example: "The global economy is showing signs of recovery.",
    vietnameseExample: "Nền kinh tế toàn cầu đang có dấu hiệu phục hồi.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_359",
    word: "Edit",
    ipa: "/ˈed.ɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To make changes to a text or film, deciding what will be removed and what will be kept in, in order to prepare it for being printed or shown.",
    vietnameseDefinition: "Chỉnh sửa",
    collocations: ["edit a video", "edit a document", "heavily edited"],
    example: "Janet edited the firm's newsletter.",
    vietnameseExample: "Janet đã chỉnh sửa bản tin của công ty.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_360",
    word: "Element",
    ipa: "/ˈel.ɪ.mənt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A part of something.",
    vietnameseDefinition: "Yếu tố, thành phần",
    collocations: ["crucial element", "key element", "element of surprise"],
    example: "List the elements that make up a perfect meal.",
    vietnameseExample: "Liệt kê các yếu tố tạo nên một bữa ăn hoàn hảo.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_361",
    word: "Eliminate",
    ipa: "/iˈlɪm.ɪ.neɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To remove or take away someone or something.",
    vietnameseDefinition: "Loại bỏ",
    collocations: ["eliminate the need", "eliminate a possibility", "completely eliminate"],
    example: "A move towards healthy eating could help eliminate heart disease.",
    vietnameseExample: "Một động thái hướng tới ăn uống lành mạnh có thể giúp loại bỏ bệnh tim.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_362",
    word: "Emerge",
    ipa: "/ɪˈmɜːdʒ/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To appear by coming out of something or out from behind something.",
    vietnameseDefinition: "Nổi lên, hiện ra",
    collocations: ["emerge from", "slowly emerge", "newly emerged"],
    example: "She emerged from the sea, blue with cold.",
    vietnameseExample: "Cô ấy nổi lên từ biển, xanh xao vì lạnh.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_363",
    word: "Emphasis",
    ipa: "/ˈem.fə.sɪs/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The particular importance or attention that is given to something.",
    vietnameseDefinition: "Sự nhấn mạnh",
    collocations: ["place emphasis on", "put emphasis on", "shift the emphasis"],
    example: "I think we should put as much emphasis on preventing disease as we do on curing it.",
    vietnameseExample: "Tôi nghĩ chúng ta nên đặt nhiều sự nhấn mạnh vào việc phòng ngừa bệnh tật cũng như chữa bệnh.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_364",
    word: "Empirical",
    ipa: "/ɪmˈpɪr.ɪ.kəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Based on what is experienced or seen rather than on theory.",
    vietnameseDefinition: "Dựa trên kinh nghiệm, thực nghiệm",
    collocations: ["empirical evidence", "empirical study", "empirical research"],
    example: "This theory needs to be backed up with solid empirical data.",
    vietnameseExample: "Lý thuyết này cần được hỗ trợ bằng dữ liệu thực nghiệm vững chắc.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_365",
    word: "Enable",
    ipa: "/ɪˈneɪ.bəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To make someone able to do something, or to make something possible.",
    vietnameseDefinition: "Cho phép, làm cho có thể",
    collocations: ["enable someone to", "enable a system", "technology enables"],
    example: "Computerization should enable us to cut production costs by half.",
    vietnameseExample: "Tin học hóa sẽ cho phép chúng ta cắt giảm một nửa chi phí sản xuất.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_366",
    word: "Encounter",
    ipa: "/ɪnˈkaʊn.tər/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A meeting, especially one that happens by chance.",
    vietnameseDefinition: "Chạm trán, bắt gặp",
    collocations: ["brief encounter", "close encounter", "encounter difficulties"],
    example: "I had an alarming encounter with a wild pig.",
    vietnameseExample: "Tôi đã có một cuộc chạm trán đáng báo động với một con lợn rừng.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_367",
    word: "Energy",
    ipa: "/ˈen.ə.dʒi/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The power and ability to be physically and mentally active.",
    vietnameseDefinition: "Năng lượng",
    collocations: ["renewable energy", "save energy", "full of energy"],
    example: "Since I started eating more healthily I've got so much more energy.",
    vietnameseExample: "Kể từ khi tôi bắt đầu ăn uống lành mạnh hơn, tôi có nhiều năng lượng hơn.",
    level: "A2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_368",
    word: "Enforce",
    ipa: "/ɪnˈfɔːs/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To make people obey a law, or to make a particular situation happen or be accepted.",
    vietnameseDefinition: "Thi hành, bắt buộc",
    collocations: ["strictly enforce", "enforce the law", "enforce a rule"],
    example: "It isn't always easy for the police to enforce speed limits.",
    vietnameseExample: "Cảnh sát không phải lúc nào cũng dễ dàng thi hành giới hạn tốc độ.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_369",
    word: "Enhance",
    ipa: "/ɪnˈhɑːns/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To improve the quality, amount, or strength of something.",
    vietnameseDefinition: "Nâng cao, cải thiện",
    collocations: ["greatly enhance", "enhance performance", "enhance the reputation"],
    example: "These scandals will not enhance the organization's reputation.",
    vietnameseExample: "Những vụ bê bối này sẽ không nâng cao danh tiếng của tổ chức.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_370",
    word: "Enormous",
    ipa: "/ɪˈnɔː.məs/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Extremely large.",
    vietnameseDefinition: "To lớn, khổng lồ",
    collocations: ["enormous amount", "enormous impact", "enormous potential"],
    example: "He earns an enormous salary.",
    vietnameseExample: "Anh ấy kiếm được một mức lương khổng lồ.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_371",
    word: "Ensure",
    ipa: "/ɪnˈʃɔːr/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To make something certain to happen.",
    vietnameseDefinition: "Đảm bảo",
    collocations: ["ensure safety", "ensure compliance", "ensure that"],
    example: "The airline is taking steps to ensure safety on its aircraft.",
    vietnameseExample: "Hãng hàng không đang thực hiện các bước để đảm bảo an toàn trên máy bay của mình.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_372",
    word: "Entity",
    ipa: "/ˈen.tɪ.ti/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Something that exists apart from other things, having its own independent existence.",
    vietnameseDefinition: "Thực thể",
    collocations: ["separate entity", "legal entity", "single entity"],
    example: "The museums work closely together, but are separate legal entities.",
    vietnameseExample: "Các bảo tàng hợp tác chặt chẽ với nhau, nhưng là các thực thể pháp lý riêng biệt.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_373",
    word: "Environment",
    ipa: "/ɪnˈvaɪ.rən.mənt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The air, water, and land in or on which people, animals, and plants live.",
    vietnameseDefinition: "Môi trường",
    collocations: ["protect the environment", "natural environment", "working environment"],
    example: "We're not doing enough to protect the environment from pollution.",
    vietnameseExample: "Chúng ta chưa làm đủ để bảo vệ môi trường khỏi ô nhiễm.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_374",
    word: "Equate",
    ipa: "/ɪˈkweɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To consider one thing to be the same as or equal to another thing.",
    vietnameseDefinition: "Đánh đồng, coi như bằng nhau",
    collocations: ["equate with", "often equate", "tend to equate"],
    example: "He complained that there was a tendency to equate right-wing politics with self-interest.",
    vietnameseExample: "Ông phàn nàn rằng có xu hướng đánh đồng chính trị cánh hữu với tư lợi.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_375",
    word: "Equip",
    ipa: "/ɪˈkwɪp/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To provide a person or a place with objects that are necessary for a particular purpose.",
    vietnameseDefinition: "Trang bị",
    collocations: ["fully equipped", "poorly equipped", "equip with"],
    example: "It's going to cost $4 million to equip the hospital.",
    vietnameseExample: "Sẽ tốn 4 triệu đô la để trang bị cho bệnh viện.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_376",
    word: "Equivalent",
    ipa: "/ɪˈkwɪv.əl.ənt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Having the same amount, value, purpose, qualities, etc.",
    vietnameseDefinition: "Tương đương",
    collocations: ["roughly equivalent", "equivalent to", "modern equivalent"],
    example: "She's doing the equivalent job in the new company but for more money.",
    vietnameseExample: "Cô ấy đang làm công việc tương đương ở công ty mới nhưng với nhiều tiền hơn.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_377",
    word: "Erode",
    ipa: "/ɪˈrəʊd/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To rub or be rubbed away gradually.",
    vietnameseDefinition: "Xói mòn, ăn mòn",
    collocations: ["gradually erode", "erode confidence", "wind erodes"],
    example: "Wind and rain have eroded the statues into shapeless lumps of stone.",
    vietnameseExample: "Gió và mưa đã xói mòn các bức tượng thành những khối đá không hình dạng.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_378",
    word: "Error",
    ipa: "/ˈer.ər/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A mistake.",
    vietnameseDefinition: "Lỗi",
    collocations: ["human error", "fatal error", "margin of error"],
    example: "He admitted that he'd made an error.",
    vietnameseExample: "Anh ấy thừa nhận rằng anh ấy đã mắc lỗi.",
    level: "A2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_379",
    word: "Establish",
    ipa: "/ɪˈstæb.lɪʃ/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To start a company or organization that will continue for a long time.",
    vietnameseDefinition: "Thành lập, thiết lập",
    collocations: ["establish a business", "firmly establish", "establish a relationship"],
    example: "The brewery was established in 1822.",
    vietnameseExample: "Nhà máy bia được thành lập vào năm 1822.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_380",
    word: "Estate",
    ipa: "/ɪˈsteɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A large area of land in the country that is owned by a family or an organization and is often used for growing crops or raising animals.",
    vietnameseDefinition: "Điền trang, bất động sản",
    collocations: ["real estate", "housing estate", "industrial estate"],
    example: "It's a typical country estate with a large house for the owner, farm buildings, and estate workers' houses.",
    vietnameseExample: "Đó là một điền trang nông thôn điển hình với một ngôi nhà lớn cho chủ sở hữu, các tòa nhà nông trại và nhà của công nhân điền trang.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_381",
    word: "Estimate",
    ipa: "/ˈes.tɪ.meɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To guess or calculate the cost, size, value, etc. of something.",
    vietnameseDefinition: "Ước tính",
    collocations: ["rough estimate", "conservative estimate", "estimate the cost"],
    example: "Government sources estimate a long-term 50 percent increase in rail fares.",
    vietnameseExample: "Các nguồn tin chính phủ ước tính giá vé đường sắt sẽ tăng 50% trong dài hạn.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_382",
    word: "Ethical",
    ipa: "/ˈeθ.ɪ.kəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Relating to beliefs about what is morally right and wrong.",
    vietnameseDefinition: "Thuộc về đạo đức",
    collocations: ["ethical standards", "ethical issue", "ethical dilemma"],
    example: "Ethical and moral issues seem to be increasingly important.",
    vietnameseExample: "Các vấn đề đạo đức và luân lý dường như ngày càng quan trọng.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_383",
    word: "Evaluate",
    ipa: "/ɪˈvæl.ju.eɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To judge or calculate the quality, importance, amount, or value of something.",
    vietnameseDefinition: "Đánh giá",
    collocations: ["carefully evaluate", "evaluate the effectiveness", "evaluate performance"],
    example: "It's impossible to evaluate these results without knowing more about the research methods employed.",
    vietnameseExample: "Không thể đánh giá những kết quả này nếu không biết thêm về các phương pháp nghiên cứu được sử dụng.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_384",
    word: "Eventual",
    ipa: "/ɪˈven.tʃu.əl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Happening or existing at a later time or at the end, especially after a lot of effort, problems, etc.",
    vietnameseDefinition: "Cuối cùng",
    collocations: ["eventual outcome", "eventual success", "eventual winner"],
    example: "The Dukes were the eventual winners of the competition.",
    vietnameseExample: "The Dukes là những người chiến thắng cuối cùng của cuộc thi.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_385",
    word: "Evident",
    ipa: "/ˈev.ɪ.dənt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Easily seen or understood.",
    vietnameseDefinition: "Hiển nhiên, rõ rệt",
    collocations: ["clearly evident", "become evident", "self-evident"],
    example: "The full extent of the damage only became evident the following morning.",
    vietnameseExample: "Mức độ thiệt hại đầy đủ chỉ trở nên rõ rệt vào sáng hôm sau.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_386",
    word: "Evolution",
    ipa: "/ˌiː.vəˈluː.ʃən/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The way in which living things change and develop over millions of years.",
    vietnameseDefinition: "Sự tiến hóa",
    collocations: ["human evolution", "theory of evolution", "gradual evolution"],
    example: "Darwin's theory of evolution",
    vietnameseExample: "Thuyết tiến hóa của Darwin",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_387",
    word: "Exceed",
    ipa: "/ɪkˈsiːd/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To be greater than a number or amount, or to go past an allowed limit.",
    vietnameseDefinition: "Vượt quá",
    collocations: ["exceed expectations", "exceed the limit", "far exceed"],
    example: "The final cost should not exceed $5,000.",
    vietnameseExample: "Chi phí cuối cùng không được vượt quá 5.000 đô la.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_388",
    word: "Exclude",
    ipa: "/ɪkˈskluːd/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To prevent someone or something from entering a place or taking part in an activity.",
    vietnameseDefinition: "Loại trừ, ngăn chặn",
    collocations: ["exclude from", "deliberately exclude", "exclude the possibility"],
    example: "Women are still excluded from the club.",
    vietnameseExample: "Phụ nữ vẫn bị loại trừ khỏi câu lạc bộ.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_389",
    word: "Exhibit",
    ipa: "/ɪɡˈzɪb.ɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To show something publicly.",
    vietnameseDefinition: "Trưng bày, triển lãm",
    collocations: ["exhibit art", "publicly exhibit", "exhibit signs of"],
    example: "He frequently exhibits at the art gallery.",
    vietnameseExample: "Anh ấy thường xuyên triển lãm tại phòng tranh.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_390",
    word: "Expansion",
    ipa: "/ɪkˈspæn.ʃən/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The increase of something in size, number, or importance.",
    vietnameseDefinition: "Sự mở rộng",
    collocations: ["rapid expansion", "business expansion", "expansion plan"],
    example: "The rapid expansion of the cities has caused social and economic problems.",
    vietnameseExample: "Sự mở rộng nhanh chóng của các thành phố đã gây ra các vấn đề kinh tế và xã hội.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_391",
    word: "Expert",
    ipa: "/ˈek.spɜːt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A person with a high level of knowledge or skill relating to a particular subject or activity.",
    vietnameseDefinition: "Chuyên gia",
    collocations: ["medical expert", "expert advice", "expert opinion"],
    example: "My mother is an expert at dress-making.",
    vietnameseExample: "Mẹ tôi là một chuyên gia may váy.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_392",
    word: "Explicit",
    ipa: "/ɪkˈsplɪs.ɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Clear and exact.",
    vietnameseDefinition: "Rõ ràng, dứt khoát",
    collocations: ["explicit instructions", "make explicit", "explicit purpose"],
    example: "I gave her very explicit directions how to get here.",
    vietnameseExample: "Tôi đã cho cô ấy chỉ dẫn rất rõ ràng làm thế nào để đến đây.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  }
];

const content = fs.readFileSync('./src/data/roadmap_vocab.ts', 'utf-8');
const arrayEnd = content.lastIndexOf(']');

let newContent = content.substring(0, arrayEnd);
if (!newContent.trim().endsWith(',')) {
    newContent += ',\n';
}

const entries = newWords.map(item => {
  return `  {
    id: "${item.id}",
    word: ${JSON.stringify(item.word)},
    ipa: ${JSON.stringify(item.ipa)},
    image: ${JSON.stringify(item.image)},
    definition: ${JSON.stringify(item.definition)},
    vietnameseDefinition: ${JSON.stringify(item.vietnameseDefinition)},
    collocations: ${JSON.stringify(item.collocations)},
    example: ${JSON.stringify(item.example)},
    vietnameseExample: ${JSON.stringify(item.vietnameseExample)},
    level: "${item.level}",
    band: ${item.band},
    topicId: "${item.topicId}"
  }`;
});

newContent += entries.join(',\n');
newContent += `\n];\n`;

fs.writeFileSync('./src/data/roadmap_vocab.ts', newContent, 'utf-8');
console.log(`Added ${newWords.length} words.`);
