import * as fs from 'fs';

const newWords = [
  {
    id: "w_b7_448",
    word: "Incompatible",
    ipa: "/ˌɪn.kəmˈpæt.ə.bəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Not able to exist or work with another person or thing because of basic differences.",
    vietnameseDefinition: "Không tương thích, kỵ nhau",
    collocations: ["totally incompatible", "incompatible with", "mutually incompatible"],
    example: "Maintaining quality is incompatible with increasing output.",
    vietnameseExample: "Duy trì chất lượng không tương thích với việc tăng sản lượng.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_449",
    word: "Incorporate",
    ipa: "/ɪnˈkɔː.pər.eɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To include something as part of something larger.",
    vietnameseDefinition: "Kết hợp, sáp nhập",
    collocations: ["incorporate into", "fully incorporate", "incorporate features"],
    example: "Suggestions from the survey have been incorporated into the final design.",
    vietnameseExample: "Các đề xuất từ cuộc khảo sát đã được kết hợp vào thiết kế cuối cùng.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_450",
    word: "Index",
    ipa: "/ˈɪn.deks/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An alphabetical list, such as one printed at the back of a book showing which page a subject, name, etc. is on.",
    vietnameseDefinition: "Chỉ mục, chỉ số",
    collocations: ["price index", "stock market index", "look up in the index"],
    example: "Try looking up 'heart disease' in the index.",
    vietnameseExample: "Hãy thử tra cứu 'bệnh tim' trong chỉ mục.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_451",
    word: "Indicate",
    ipa: "/ˈɪn.dɪ.keɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To show, point, or make clear in another way.",
    vietnameseDefinition: "Chỉ ra, biểu thị",
    collocations: ["clearly indicate", "indicate a preference", "evidence indicates"],
    example: "Exploratory investigations have indicated large amounts of oil below the sea bed.",
    vietnameseExample: "Các cuộc điều tra thăm dò đã chỉ ra một lượng lớn dầu dưới đáy biển.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_452",
    word: "Individual",
    ipa: "/ˌɪn.dɪˈvɪdʒ.u.əl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A single person or thing, especially when compared to the group or set to which they belong.",
    vietnameseDefinition: "Cá nhân",
    collocations: ["individual needs", "individual differences", "private individual"],
    example: "Every individual has rights which must never be taken away.",
    vietnameseExample: "Mỗi cá nhân đều có những quyền không bao giờ được tước đoạt.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_453",
    word: "Induce",
    ipa: "/ɪnˈdʒuːs/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To persuade someone to do something, or to cause something to happen.",
    vietnameseDefinition: "Xui khiến, gây ra",
    collocations: ["induce sleep", "induce a response", "induce labour"],
    example: "They induced her to take the job by promising editorial freedom.",
    vietnameseExample: "Họ đã xui khiến cô nhận công việc bằng cách hứa hẹn quyền tự do biên tập.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_454",
    word: "Inevitable",
    ipa: "/ɪˈnev.ɪ.tə.bəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Certain to happen and unable to be avoided or prevented.",
    vietnameseDefinition: "Không thể tránh khỏi",
    collocations: ["inevitable consequence", "inevitable result", "almost inevitable"],
    example: "The accident was the inevitable consequence of carelessness.",
    vietnameseExample: "Tai nạn là hậu quả không thể tránh khỏi của sự bất cẩn.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_455",
    word: "Infer",
    ipa: "/ɪnˈfɜːr/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To form an opinion or guess that something is true because of the information that you have.",
    vietnameseDefinition: "Suy ra, luận ra",
    collocations: ["infer from", "reasonably infer", "infer a meaning"],
    example: "What do you infer from her refusal?",
    vietnameseExample: "Bạn suy ra điều gì từ sự từ chối của cô ấy?",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_456",
    word: "Infrastructure",
    ipa: "/ˈɪn.frəˌstrʌk.tʃər/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The basic systems and services, such as transport and power supplies, that a country or organization uses in order to work effectively.",
    vietnameseDefinition: "Cơ sở hạ tầng",
    collocations: ["transport infrastructure", "crumbling infrastructure", "invest in infrastructure"],
    example: "The war has badly damaged the country's infrastructure.",
    vietnameseExample: "Chiến tranh đã làm hư hại nặng nề cơ sở hạ tầng của đất nước.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_457",
    word: "Inherent",
    ipa: "/ɪnˈher.ənt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Existing as a natural or basic part of something.",
    vietnameseDefinition: "Vốn có, cố hữu",
    collocations: ["inherent danger", "inherent weakness", "inherent in"],
    example: "There are dangers/risks inherent in almost every sport.",
    vietnameseExample: "Có những nguy hiểm/rủi ro vốn có trong hầu hết mọi môn thể thao.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_458",
    word: "Inhibit",
    ipa: "/ɪnˈhɪb.ɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To prevent someone from doing something by making them feel nervous or embarrassed.",
    vietnameseDefinition: "Ngăn chặn, kiềm chế",
    collocations: ["inhibit growth", "inhibit development", "severely inhibit"],
    example: "Some workers were inhibited (from speaking) by the presence of their managers.",
    vietnameseExample: "Một số công nhân bị kiềm chế (không dám nói) bởi sự hiện diện của người quản lý của họ.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_459",
    word: "Initial",
    ipa: "/ɪˈnɪʃ.əl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Of or at the beginning.",
    vietnameseDefinition: "Ban đầu",
    collocations: ["initial reaction", "initial stage", "initial cost"],
    example: "My initial surprise was soon replaced by delight.",
    vietnameseExample: "Sự ngạc nhiên ban đầu của tôi nhanh chóng được thay thế bằng sự vui mừng.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_460",
    word: "Initiate",
    ipa: "/ɪˈnɪʃ.i.eɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To cause something to begin.",
    vietnameseDefinition: "Khởi xướng, bắt đầu",
    collocations: ["initiate a project", "initiate a discussion", "formally initiate"],
    example: "Who initiated the violence?",
    vietnameseExample: "Ai đã khởi xướng bạo lực?",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_461",
    word: "Injure",
    ipa: "/ˈɪn.dʒər/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To hurt or cause physical harm to a person or animal.",
    vietnameseDefinition: "Làm bị thương",
    collocations: ["seriously injure", "fatally injure", "injure pride"],
    example: "She fell and injured her shoulder.",
    vietnameseExample: "Cô ấy bị ngã và làm bị thương vai.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_462",
    word: "Innovate",
    ipa: "/ˈɪn.ə.veɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To introduce changes and new ideas.",
    vietnameseDefinition: "Đổi mới",
    collocations: ["innovate in", "continue to innovate", "need to innovate"],
    example: "The fashion industry is always desperate to innovate.",
    vietnameseExample: "Ngành công nghiệp thời trang luôn khao khát đổi mới.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_463",
    word: "Input",
    ipa: "/ˈɪn.pʊt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Something such as energy, money, or information that is put into a system, organization, or machine so that it can operate.",
    vietnameseDefinition: "Đầu vào, sự đóng góp",
    collocations: ["valuable input", "require input", "data input"],
    example: "I didn't have much input into the project.",
    vietnameseExample: "Tôi không có nhiều đóng góp vào dự án.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_464",
    word: "Insert",
    ipa: "/ɪnˈsɜːt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To put something inside something else.",
    vietnameseDefinition: "Chèn vào, lồng vào",
    collocations: ["insert a coin", "insert a document", "insert into"],
    example: "Insert the key in/into the lock.",
    vietnameseExample: "Chèn chìa khóa vào ổ khóa.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_465",
    word: "Insight",
    ipa: "/ˈɪn.saɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A clear, deep, and sometimes sudden understanding of a complicated problem or situation.",
    vietnameseDefinition: "Sự thấu hiểu, cái nhìn sâu sắc",
    collocations: ["gain insight", "provide insight", "valuable insight"],
    example: "It was an interesting book, full of fascinating insights into human relationships.",
    vietnameseExample: "Đó là một cuốn sách thú vị, đầy những cái nhìn sâu sắc hấp dẫn về các mối quan hệ của con người.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_466",
    word: "Inspect",
    ipa: "/ɪnˈspekt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To look at something or someone carefully in order to discover information, especially about their quality or condition.",
    vietnameseDefinition: "Kiểm tra, thanh tra",
    collocations: ["closely inspect", "regularly inspect", "inspect for damage"],
    example: "After the crash both drivers got out and inspected their cars for damage.",
    vietnameseExample: "Sau vụ va chạm, cả hai tài xế đều bước ra và kiểm tra xe của họ xem có bị hư hỏng không.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_467",
    word: "Instance",
    ipa: "/ˈɪn.stəns/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A particular situation, event, or fact, especially an example of something that happens generally.",
    vietnameseDefinition: "Ví dụ, trường hợp",
    collocations: ["for instance", "in this instance", "rare instance"],
    example: "There have been several instances of violence at the school.",
    vietnameseExample: "Đã có một vài trường hợp bạo lực tại trường học.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_468",
    word: "Institute",
    ipa: "/ˈɪn.stɪ.tʃuːt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An organization where people do a particular type of scientific, educational, or social work, or the buildings that it uses.",
    vietnameseDefinition: "Viện, học viện",
    collocations: ["research institute", "art institute", "found an institute"],
    example: "The Massachusetts Institute of Technology",
    vietnameseExample: "Viện Công nghệ Massachusetts",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_469",
    word: "Instruct",
    ipa: "/ɪnˈstrʌkt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To order or tell someone to do something, especially in a formal way.",
    vietnameseDefinition: "Chỉ thị, hướng dẫn",
    collocations: ["instruct someone to", "strictly instruct", "instruct a lawyer"],
    example: "The police have been instructed to patrol the building and surrounding area.",
    vietnameseExample: "Cảnh sát đã được chỉ thị tuần tra tòa nhà và khu vực xung quanh.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_470",
    word: "Integral",
    ipa: "/ˈɪn.tɪ.ɡrəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Necessary and important as a part of a whole.",
    vietnameseDefinition: "Không thể thiếu, trọn vẹn",
    collocations: ["integral part", "integral component", "integral to"],
    example: "He's an integral part of the team and we can't do without him.",
    vietnameseExample: "Anh ấy là một phần không thể thiếu của đội và chúng tôi không thể làm gì nếu không có anh ấy.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_471",
    word: "Integrate",
    ipa: "/ˈɪn.tɪ.ɡreɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To mix with and join society or a group of people, often changing to suit their way of life, habits, and customs.",
    vietnameseDefinition: "Hội nhập, tích hợp",
    collocations: ["integrate into", "fully integrate", "integrate with"],
    example: "It's very difficult to integrate yourself into a society whose culture is so different from your own.",
    vietnameseExample: "Rất khó để hòa nhập vào một xã hội có nền văn hóa quá khác biệt với nền văn hóa của bạn.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_472",
    word: "Integrity",
    ipa: "/ɪnˈteɡ.rə.ti/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The quality of being honest and having strong moral principles that you refuse to change.",
    vietnameseDefinition: "Sự chính trực, tính toàn vẹn",
    collocations: ["personal integrity", "professional integrity", "maintain integrity"],
    example: "No one doubted that the president was a man of the highest integrity.",
    vietnameseExample: "Không ai nghi ngờ rằng tổng thống là một người có sự chính trực cao nhất.",
    level: "C2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_473",
    word: "Intelligence",
    ipa: "/ɪnˈtel.ɪ.dʒəns/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The ability to learn, understand, and make judgments or have opinions that are based on reason.",
    vietnameseDefinition: "Trí thông minh",
    collocations: ["artificial intelligence", "high intelligence", "intelligence test"],
    example: "It's the intelligence of her writing that impresses me.",
    vietnameseExample: "Chính sự thông minh trong bài viết của cô ấy đã gây ấn tượng với tôi.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_474",
    word: "Intense",
    ipa: "/ɪnˈtens/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Extreme and forceful or (of a feeling) very strong.",
    vietnameseDefinition: "Mãnh liệt, dữ dội",
    collocations: ["intense pressure", "intense heat", "intense debate"],
    example: "He suddenly felt an intense pain in his back.",
    vietnameseExample: "Anh đột nhiên cảm thấy một cơn đau dữ dội ở lưng.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_475",
    word: "Interact",
    ipa: "/ˌɪn.təˈrækt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To communicate with or react to.",
    vietnameseDefinition: "Tương tác",
    collocations: ["interact with", "interact closely", "socially interact"],
    example: "Dominic's teacher says that he interacts well with the other children.",
    vietnameseExample: "Giáo viên của Dominic nói rằng cậu bé tương tác tốt với những đứa trẻ khác.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_476",
    word: "Intermediate",
    ipa: "/ˌɪn.təˈmiː.di.ət/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Being between two other related things, levels, or points.",
    vietnameseDefinition: "Trung cấp, ở giữa",
    collocations: ["intermediate level", "intermediate stage", "intermediate step"],
    example: "There are three levels of difficulty in this game: low, intermediate, and high.",
    vietnameseExample: "Có ba mức độ khó trong trò chơi này: thấp, trung bình và cao.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_477",
    word: "Internal",
    ipa: "/ɪnˈtɜː.nəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Existing or happening inside a person, object, organization, place, or country.",
    vietnameseDefinition: "Nội bộ, bên trong",
    collocations: ["internal organs", "internal affairs", "internal market"],
    example: "He sustained injuries to his internal organs.",
    vietnameseExample: "Anh ấy bị thương ở các cơ quan nội tạng.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_478",
    word: "Interpret",
    ipa: "/ɪnˈtɜː.prɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To decide what the intended meaning of something is.",
    vietnameseDefinition: "Giải thích, phiên dịch",
    collocations: ["interpret data", "interpret a dream", "difficult to interpret"],
    example: "It's difficult to interpret these statistics without knowing how they were obtained.",
    vietnameseExample: "Rất khó để giải thích những số liệu thống kê này nếu không biết chúng được thu thập như thế nào.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_479",
    word: "Interval",
    ipa: "/ˈɪn.tə.vəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A period between two events or times.",
    vietnameseDefinition: "Khoảng thời gian, lúc nghỉ",
    collocations: ["regular intervals", "brief interval", "time interval"],
    example: "We see each other at regular intervals - usually about once a month.",
    vietnameseExample: "Chúng tôi gặp nhau đều đặn - thường là khoảng một tháng một lần.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_480",
    word: "Intervene",
    ipa: "/ˌɪn.təˈviːn/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To intentionally become involved in a difficult situation in order to improve it or prevent it from getting worse.",
    vietnameseDefinition: "Can thiệp",
    collocations: ["intervene in", "directly intervene", "military intervene"],
    example: "The Central Bank intervened in the currency markets today to try to stabilize the exchange rate.",
    vietnameseExample: "Ngân hàng Trung ương đã can thiệp vào thị trường tiền tệ hôm nay để cố gắng ổn định tỷ giá hối đoái.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_481",
    word: "Intrinsic",
    ipa: "/ɪnˈtrɪn.zɪk/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Being an extremely important and basic characteristic of a person or thing.",
    vietnameseDefinition: "Bản chất, thực chất",
    collocations: ["intrinsic value", "intrinsic part", "intrinsic motivation"],
    example: "Maths is an intrinsic part of the school curriculum.",
    vietnameseExample: "Toán học là một phần bản chất của chương trình giảng dạy ở trường.",
    level: "C2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_482",
    word: "Invest",
    ipa: "/ɪnˈvest/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To put money, effort, time, etc. into something to make a profit or get an advantage.",
    vietnameseDefinition: "Đầu tư",
    collocations: ["invest heavily", "invest in", "invest time"],
    example: "The institute will invest five million in the project.",
    vietnameseExample: "Viện sẽ đầu tư năm triệu vào dự án.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_483",
    word: "Investigate",
    ipa: "/ɪnˈves.tɪ.ɡeɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To examine a crime, problem, statement, etc. carefully, especially to discover the truth.",
    vietnameseDefinition: "Điều tra",
    collocations: ["investigate thoroughly", "investigate a crime", "investigate the cause"],
    example: "Police are investigating allegations of corruption involving senior executives.",
    vietnameseExample: "Cảnh sát đang điều tra các cáo buộc tham nhũng liên quan đến các giám đốc điều hành cấp cao.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_484",
    word: "Invoke",
    ipa: "/ɪnˈvəʊk/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To use a law in order to achieve something, or to mention something in order to explain something or to support your opinion or action.",
    vietnameseDefinition: "Viện dẫn, gọi ra",
    collocations: ["invoke a rule", "invoke a law", "invoke memories"],
    example: "Police can invoke the law to regulate access to these places.",
    vietnameseExample: "Cảnh sát có thể viện dẫn luật để điều chỉnh việc tiếp cận những nơi này.",
    level: "C2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_485",
    word: "Involve",
    ipa: "/ɪnˈvɒlv/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "If an activity, situation, etc. involves something, that thing is a part of the activity, etc.",
    vietnameseDefinition: "Bao gồm, liên quan",
    collocations: ["heavily involve", "involve in", "involve a risk"],
    example: "The operation involves putting a small tube into your heart.",
    vietnameseExample: "Cuộc phẫu thuật bao gồm việc đưa một ống nhỏ vào tim bạn.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_486",
    word: "Isolate",
    ipa: "/ˈaɪ.sə.leɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To separate something from other things with which it is connected or mixed.",
    vietnameseDefinition: "Cô lập, cách ly",
    collocations: ["completely isolate", "isolate from", "isolate the cause"],
    example: "A high wall isolated the house from the rest of the village.",
    vietnameseExample: "Một bức tường cao đã cô lập ngôi nhà khỏi phần còn lại của ngôi làng.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_487",
    word: "Issue",
    ipa: "/ˈɪʃ.uː/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A subject or problem that people are thinking and talking about.",
    vietnameseDefinition: "Vấn đề",
    collocations: ["key issue", "major issue", "address an issue"],
    example: "Environmental issues are currently high on the political agenda.",
    vietnameseExample: "Các vấn đề môi trường hiện đang được đặt lên hàng đầu trong chương trình nghị sự chính trị.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_488",
    word: "Item",
    ipa: "/ˈaɪ.təm/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Something that is part of a list or group of things.",
    vietnameseDefinition: "Món đồ, khoản",
    collocations: ["collector's item", "luxury item", "item on the agenda"],
    example: "The restaurant has a long menu of about 50 items.",
    vietnameseExample: "Nhà hàng có một thực đơn dài khoảng 50 món.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_489",
    word: "Job",
    ipa: "/dʒɒb/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The regular work that a person does to earn money.",
    vietnameseDefinition: "Công việc",
    collocations: ["full-time job", "part-time job", "apply for a job"],
    example: "She got a job in a bank.",
    vietnameseExample: "Cô ấy đã nhận được một công việc trong một ngân hàng.",
    level: "A1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_490",
    word: "Journal",
    ipa: "/ˈdʒɜː.nəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A serious magazine or newspaper that is published regularly about a particular subject.",
    vietnameseDefinition: "Tạp chí (chuyên ngành)",
    collocations: ["medical journal", "academic journal", "scientific journal"],
    example: "He has published several papers in leading scientific journals.",
    vietnameseExample: "Ông đã công bố một số bài báo trên các tạp chí khoa học hàng đầu.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_491",
    word: "Justify",
    ipa: "/ˈdʒʌs.tɪ.faɪ/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To show that something is reasonable, right, or true.",
    vietnameseDefinition: "Biện minh, chứng minh là đúng",
    collocations: ["justify a decision", "justify an action", "hard to justify"],
    example: "I can't really justify taking another day off work.",
    vietnameseExample: "Tôi thực sự không thể biện minh cho việc nghỉ thêm một ngày làm việc.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_492",
    word: "Label",
    ipa: "/ˈleɪ.bəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A piece of paper or other material that gives you information about the object it is attached to.",
    vietnameseDefinition: "Nhãn mác",
    collocations: ["designer label", "warning label", "read the label"],
    example: "Remember to put some address labels on the suitcases.",
    vietnameseExample: "Nhớ dán một số nhãn địa chỉ lên vali.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_493",
    word: "Labour",
    ipa: "/ˈleɪ.bər/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Practical work, especially when it involves hard physical effort.",
    vietnameseDefinition: "Lao động",
    collocations: ["manual labour", "cheap labour", "labour market"],
    example: "The car parts themselves are not expensive, it's the labour that costs the money.",
    vietnameseExample: "Bản thân các bộ phận ô tô không đắt, chính sức lao động mới tốn tiền.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_494",
    word: "Layer",
    ipa: "/ˈleɪ.ər/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A level of material, such as a type of rock or gas, that is different from the material above or below it.",
    vietnameseDefinition: "Lớp",
    collocations: ["thin layer", "thick layer", "ozone layer"],
    example: "A thick layer of clay lies over the sandstone.",
    vietnameseExample: "Một lớp đất sét dày nằm trên đá sa thạch.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_495",
    word: "Legislate",
    ipa: "/ˈledʒ.ɪ.sleɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To make a law.",
    vietnameseDefinition: "Lập pháp, làm luật",
    collocations: ["legislate against", "legislate for", "power to legislate"],
    example: "They promised to legislate against cigarette advertising.",
    vietnameseExample: "Họ hứa sẽ lập pháp chống lại quảng cáo thuốc lá.",
    level: "C2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_496",
    word: "Levy",
    ipa: "/ˈlev.i/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An amount of money, such as a tax, that you have to pay to a government or organization.",
    vietnameseDefinition: "Thuế, sự thu thuế",
    collocations: ["impose a levy", "tax levy", "pay a levy"],
    example: "They imposed a five percent levy on alcohol.",
    vietnameseExample: "Họ đã áp dụng mức thuế năm phần trăm đối với rượu.",
    level: "C2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_497",
    word: "Liberal",
    ipa: "/ˈlɪb.ər.əl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Respecting and allowing many different types of beliefs or behaviour.",
    vietnameseDefinition: "Tự do, phóng khoáng",
    collocations: ["liberal attitude", "liberal views", "liberal democracy"],
    example: "Her parents were very liberal and allowed her a lot of freedom.",
    vietnameseExample: "Cha mẹ cô ấy rất phóng khoáng và cho phép cô ấy nhiều tự do.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_498",
    word: "Licence",
    ipa: "/ˈlaɪ.səns/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An official document that gives you permission to own, do, or use something.",
    vietnameseDefinition: "Giấy phép",
    collocations: ["driving licence", "apply for a licence", "revoke a licence"],
    example: "He was caught driving without a licence.",
    vietnameseExample: "Anh ta bị bắt quả tang lái xe không có giấy phép.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_499",
    word: "Logic",
    ipa: "/ˈlɒdʒ.ɪk/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A particular way of thinking, especially one that is reasonable and based on good judgment.",
    vietnameseDefinition: "Logic, lý lẽ",
    collocations: ["flawed logic", "simple logic", "defy logic"],
    example: "I fail to see the logic behind his argument.",
    vietnameseExample: "Tôi không thấy được logic đằng sau lập luận của anh ấy.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_500",
    word: "Margin",
    ipa: "/ˈmɑː.dʒɪn/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The amount by which one thing is different from another.",
    vietnameseDefinition: "Lề, mức chênh lệch",
    collocations: ["profit margin", "narrow margin", "margin of error"],
    example: "The Senate approved the use of military force by a margin of 52 votes to 47.",
    vietnameseExample: "Thượng viện đã chấp thuận việc sử dụng lực lượng quân sự với tỷ lệ chênh lệch 52 phiếu thuận và 47 phiếu chống.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  }
];

const content = fs.readFileSync('./src/data/roadmap_vocab.ts', 'utf-8');
const arrayEnd = content.lastIndexOf(']');

let newContent = content.substring(0, arrayEnd);
if (!newContent.trim().endsWith(',')) {
    newContent += ',\n';
}

const entries = newWords.map(item => {
  return `  {
    id: "${item.id}",
    word: ${JSON.stringify(item.word)},
    ipa: ${JSON.stringify(item.ipa)},
    image: ${JSON.stringify(item.image)},
    definition: ${JSON.stringify(item.definition)},
    vietnameseDefinition: ${JSON.stringify(item.vietnameseDefinition)},
    collocations: ${JSON.stringify(item.collocations)},
    example: ${JSON.stringify(item.example)},
    vietnameseExample: ${JSON.stringify(item.vietnameseExample)},
    level: "${item.level}",
    band: ${item.band},
    topicId: "${item.topicId}"
  }`;
});

newContent += entries.join(',\n');
newContent += `\n];\n`;

fs.writeFileSync('./src/data/roadmap_vocab.ts', newContent, 'utf-8');
console.log(`Added ${newWords.length} words.`);
