import * as fs from 'fs';

const newWords = [
  {
    id: "w_b7_393",
    word: "Exploit",
    ipa: "/ɪkˈsplɔɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To use something in a way that helps you.",
    vietnameseDefinition: "Khai thác, bóc lột",
    collocations: ["exploit resources", "commercially exploit", "exploit an opportunity"],
    example: "We need to make sure that we exploit our resources as fully as possible.",
    vietnameseExample: "Chúng ta cần đảm bảo rằng chúng ta khai thác tài nguyên của mình một cách triệt để nhất có thể.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_394",
    word: "Export",
    ipa: "/ɪkˈspɔːt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To send goods to another country for sale.",
    vietnameseDefinition: "Xuất khẩu",
    collocations: ["export goods", "export market", "major export"],
    example: "French cheeses are exported to many different countries.",
    vietnameseExample: "Phô mai Pháp được xuất khẩu sang nhiều quốc gia khác nhau.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_395",
    word: "Expose",
    ipa: "/ɪkˈspəʊz/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To remove what is covering something so that it can be seen.",
    vietnameseDefinition: "Phơi bày, tiếp xúc",
    collocations: ["expose to", "expose the truth", "highly exposed"],
    example: "He damaged his leg so badly in the accident that the bone was exposed.",
    vietnameseExample: "Anh ấy bị thương ở chân nặng đến mức xương bị phơi bày ra ngoài.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_396",
    word: "Extract",
    ipa: "/ɪkˈstrækt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To remove or take out something.",
    vietnameseDefinition: "Chiết xuất, trích xuất",
    collocations: ["extract information", "extract from", "extract a tooth"],
    example: "They used to extract iron ore from this site.",
    vietnameseExample: "Họ từng khai thác quặng sắt từ địa điểm này.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_397",
    word: "Facilitate",
    ipa: "/fəˈsɪl.ɪ.teɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To make something possible or easier.",
    vietnameseDefinition: "Tạo điều kiện, làm cho dễ dàng",
    collocations: ["facilitate learning", "facilitate growth", "help to facilitate"],
    example: "The new ramp will facilitate the entry of wheelchairs.",
    vietnameseExample: "Đoạn đường nối mới sẽ tạo điều kiện cho xe lăn đi vào.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_398",
    word: "Factor",
    ipa: "/ˈfæk.tər/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A fact or situation that influences the result of something.",
    vietnameseDefinition: "Yếu tố",
    collocations: ["key factor", "deciding factor", "contributing factor"],
    example: "Price will be a major factor in the success of this new product.",
    vietnameseExample: "Giá cả sẽ là một yếu tố chính trong sự thành công của sản phẩm mới này.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_399",
    word: "Feature",
    ipa: "/ˈfiː.tʃər/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A typical quality or an important part of something.",
    vietnameseDefinition: "Đặc điểm, tính năng",
    collocations: ["key feature", "main feature", "distinctive feature"],
    example: "The town's main features are its beautiful mosque and ancient marketplace.",
    vietnameseExample: "Đặc điểm chính của thị trấn là nhà thờ Hồi giáo xinh đẹp và khu chợ cổ.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_400",
    word: "Federal",
    ipa: "/ˈfed.ər.əl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Relating to the central government, and not to the government of a region.",
    vietnameseDefinition: "Thuộc liên bang",
    collocations: ["federal government", "federal law", "federal agency"],
    example: "The federal government is responsible for national defense.",
    vietnameseExample: "Chính phủ liên bang chịu trách nhiệm về quốc phòng.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_401",
    word: "Fee",
    ipa: "/fiː/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An amount of money paid for a particular piece of work or for a particular right or service.",
    vietnameseDefinition: "Lệ phí, học phí",
    collocations: ["pay a fee", "tuition fee", "legal fee"],
    example: "University fees are expected to rise again next year.",
    vietnameseExample: "Học phí đại học dự kiến sẽ tăng trở lại vào năm tới.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_402",
    word: "File",
    ipa: "/faɪl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Any of several different types of container used to store papers, letters, and other documents in an ordered way.",
    vietnameseDefinition: "Hồ sơ, tệp tin",
    collocations: ["keep on file", "computer file", "open a file"],
    example: "I've lost a file containing a lot of important documents.",
    vietnameseExample: "Tôi đã làm mất một tệp chứa nhiều tài liệu quan trọng.",
    level: "A2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_403",
    word: "Final",
    ipa: "/ˈfaɪ.nəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Last.",
    vietnameseDefinition: "Cuối cùng",
    collocations: ["final decision", "final stage", "final result"],
    example: "The project is in its final stages.",
    vietnameseExample: "Dự án đang ở giai đoạn cuối cùng.",
    level: "A2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_404",
    word: "Finance",
    ipa: "/ˈfaɪ.næns/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The management of large amounts of money, especially by governments or large companies.",
    vietnameseDefinition: "Tài chính",
    collocations: ["personal finance", "corporate finance", "raise finance"],
    example: "You need to speak to someone in the finance department.",
    vietnameseExample: "Bạn cần nói chuyện với ai đó ở phòng tài chính.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_405",
    word: "Finite",
    ipa: "/ˈfaɪ.naɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Having a limit or end.",
    vietnameseDefinition: "Có hạn",
    collocations: ["finite resources", "finite amount", "finite space"],
    example: "The funds available for the health service are finite and we cannot afford to waste money.",
    vietnameseExample: "Các quỹ dành cho dịch vụ y tế là có hạn và chúng ta không thể lãng phí tiền bạc.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_406",
    word: "Flexibility",
    ipa: "/ˌflek.səˈbɪl.ə.ti/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The ability to change or be changed easily according to the situation.",
    vietnameseDefinition: "Sự linh hoạt",
    collocations: ["great flexibility", "offer flexibility", "require flexibility"],
    example: "The advantage of this system is its flexibility.",
    vietnameseExample: "Ưu điểm của hệ thống này là sự linh hoạt của nó.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_407",
    word: "Fluctuate",
    ipa: "/ˈflʌk.tʃu.eɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To change, especially continuously and between one level or thing and another.",
    vietnameseDefinition: "Dao động, biến động",
    collocations: ["fluctuate wildly", "fluctuate between", "prices fluctuate"],
    example: "Vegetable prices fluctuate according to the season.",
    vietnameseExample: "Giá rau dao động theo mùa.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_408",
    word: "Focus",
    ipa: "/ˈfəʊ.kəs/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The main or central point of something, especially of attention or interest.",
    vietnameseDefinition: "Trọng tâm, tập trung",
    collocations: ["main focus", "focus of attention", "lose focus"],
    example: "I think we've lost focus on what we're trying to achieve.",
    vietnameseExample: "Tôi nghĩ chúng ta đã mất tập trung vào những gì chúng ta đang cố gắng đạt được.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_409",
    word: "Format",
    ipa: "/ˈfɔː.mæt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A pattern, plan, or arrangement.",
    vietnameseDefinition: "Định dạng, hình thức",
    collocations: ["standard format", "change the format", "in a format"],
    example: "The meeting will have the usual format.",
    vietnameseExample: "Cuộc họp sẽ có hình thức thông thường.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_410",
    word: "Formula",
    ipa: "/ˈfɔː.mjə.lə/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A standard or accepted way of doing or making something.",
    vietnameseDefinition: "Công thức",
    collocations: ["winning formula", "magic formula", "mathematical formula"],
    example: "There's no magic formula for success.",
    vietnameseExample: "Không có công thức kỳ diệu nào cho sự thành công.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_411",
    word: "Forthcoming",
    ipa: "/ˌfɔːθˈkʌm.ɪŋ/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Happening or appearing soon.",
    vietnameseDefinition: "Sắp tới",
    collocations: ["forthcoming elections", "forthcoming events", "forthcoming book"],
    example: "We have just received the information about the forthcoming conference.",
    vietnameseExample: "Chúng tôi vừa nhận được thông tin về hội nghị sắp tới.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_412",
    word: "Foundation",
    ipa: "/faʊnˈdeɪ.ʃən/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An underlying basis or principle for something.",
    vietnameseDefinition: "Nền tảng, sự thành lập",
    collocations: ["lay the foundation", "solid foundation", "without foundation"],
    example: "Respect and friendship provide a solid foundation for marriage.",
    vietnameseExample: "Sự tôn trọng và tình bạn cung cấp một nền tảng vững chắc cho hôn nhân.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_413",
    word: "Found",
    ipa: "/faʊnd/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To bring something into existence.",
    vietnameseDefinition: "Thành lập",
    collocations: ["found a company", "found an organization", "newly founded"],
    example: "Boston was founded in 1630 by Puritan colonists from England.",
    vietnameseExample: "Boston được thành lập vào năm 1630 bởi những người thực dân Thanh giáo từ Anh.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_414",
    word: "Framework",
    ipa: "/ˈfreɪm.wɜːk/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A system of rules, ideas, or beliefs that is used to plan or decide something.",
    vietnameseDefinition: "Khuôn khổ, cơ cấu",
    collocations: ["legal framework", "theoretical framework", "provide a framework"],
    example: "The agreement provides a framework for future negotiations.",
    vietnameseExample: "Thỏa thuận này cung cấp một khuôn khổ cho các cuộc đàm phán trong tương lai.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_415",
    word: "Function",
    ipa: "/ˈfʌŋk.ʃən/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The natural purpose (of something) or the duty (of a person).",
    vietnameseDefinition: "Chức năng",
    collocations: ["main function", "vital function", "perform a function"],
    example: "The function of the veins is to carry blood to the heart.",
    vietnameseExample: "Chức năng của tĩnh mạch là mang máu về tim.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_416",
    word: "Fund",
    ipa: "/fʌnd/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An amount of money saved, collected, or provided for a particular purpose.",
    vietnameseDefinition: "Quỹ, tài trợ",
    collocations: ["pension fund", "relief fund", "raise funds"],
    example: "The hospital has set up a special fund to buy new equipment.",
    vietnameseExample: "Bệnh viện đã lập một quỹ đặc biệt để mua thiết bị mới.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_417",
    word: "Fundamental",
    ipa: "/ˌfʌn.dəˈmen.təl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Forming the base, from which everything else develops.",
    vietnameseDefinition: "Cơ bản, nền tảng",
    collocations: ["fundamental difference", "fundamental change", "fundamental right"],
    example: "We need to make fundamental changes to the way in which we treat our environment.",
    vietnameseExample: "Chúng ta cần thực hiện những thay đổi cơ bản đối với cách chúng ta đối xử với môi trường của mình.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_418",
    word: "Furthermore",
    ipa: "/ˌfɜː.ðəˈmɔːr/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "In addition; more importantly.",
    vietnameseDefinition: "Hơn nữa, vả lại",
    collocations: ["and furthermore"],
    example: "The house is beautiful. Furthermore, it's in a great location.",
    vietnameseExample: "Ngôi nhà rất đẹp. Hơn nữa, nó ở một vị trí tuyệt vời.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_419",
    word: "Gender",
    ipa: "/ˈdʒen.dər/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The physical and/or social condition of being male or female.",
    vietnameseDefinition: "Giới tính",
    collocations: ["gender equality", "gender roles", "gender discrimination"],
    example: "Does this test show the gender of the baby?",
    vietnameseExample: "Xét nghiệm này có cho biết giới tính của em bé không?",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_420",
    word: "Generate",
    ipa: "/ˈdʒen.ə.reɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To cause something to exist.",
    vietnameseDefinition: "Tạo ra, phát sinh",
    collocations: ["generate income", "generate electricity", "generate interest"],
    example: "Her latest film has generated a lot of interest.",
    vietnameseExample: "Bộ phim mới nhất của cô ấy đã tạo ra rất nhiều sự quan tâm.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_421",
    word: "Generation",
    ipa: "/ˌdʒen.əˈreɪ.ʃən/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "All the people of about the same age within a society or within a particular family.",
    vietnameseDefinition: "Thế hệ",
    collocations: ["younger generation", "future generations", "generation gap"],
    example: "The younger generation smokes less than their parents did.",
    vietnameseExample: "Thế hệ trẻ hút thuốc ít hơn cha mẹ của họ.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_422",
    word: "Globe",
    ipa: "/ɡləʊb/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "The world.",
    vietnameseDefinition: "Địa cầu, thế giới",
    collocations: ["across the globe", "around the globe", "global warming"],
    example: "She is a superstar all around the globe.",
    vietnameseExample: "Cô ấy là một siêu sao trên toàn cầu.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_423",
    word: "Goal",
    ipa: "/ɡəʊl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An aim or purpose.",
    vietnameseDefinition: "Mục tiêu",
    collocations: ["achieve a goal", "set a goal", "ultimate goal"],
    example: "Our ultimate goal must be the preservation of the environment.",
    vietnameseExample: "Mục tiêu cuối cùng của chúng ta phải là bảo tồn môi trường.",
    level: "A2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_424",
    word: "Grade",
    ipa: "/ɡreɪd/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A level of quality, size, importance, etc.",
    vietnameseDefinition: "Cấp bậc, điểm số",
    collocations: ["high grade", "top grade", "pay grade"],
    example: "He's suffering from some kind of low-grade infection.",
    vietnameseExample: "Anh ấy đang bị một loại nhiễm trùng cấp độ thấp nào đó.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_425",
    word: "Grant",
    ipa: "/ɡrɑːnt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An amount of money given especially by the government to a person or organization for a special purpose.",
    vietnameseDefinition: "Trợ cấp, ban cho",
    collocations: ["government grant", "student grant", "take for granted"],
    example: "They gave her a grant to study abroad for one year.",
    vietnameseExample: "Họ đã cho cô ấy một khoản trợ cấp để đi du học trong một năm.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_426",
    word: "Guarantee",
    ipa: "/ˌɡær.ənˈtiː/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A promise that something will be done or will happen.",
    vietnameseDefinition: "Đảm bảo, bảo hành",
    collocations: ["money-back guarantee", "under guarantee", "offer a guarantee"],
    example: "The system costs less and comes with a money-back guarantee.",
    vietnameseExample: "Hệ thống này có giá thấp hơn và đi kèm với sự đảm bảo hoàn tiền.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_427",
    word: "Guideline",
    ipa: "/ˈɡaɪd.laɪn/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Information intended to advise people on how something should be done or what something should be.",
    vietnameseDefinition: "Hướng dẫn, nguyên tắc chỉ đạo",
    collocations: ["strict guidelines", "clear guidelines", "issue guidelines"],
    example: "The EU has issued guidelines on appropriate levels of pay for part-time manual workers.",
    vietnameseExample: "EU đã ban hành các hướng dẫn về mức lương phù hợp cho công nhân thủ công bán thời gian.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_428",
    word: "Hence",
    ipa: "/hens/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "That is the reason or explanation for.",
    vietnameseDefinition: "Do đó, vì thế",
    collocations: ["hence the name", "hence the need"],
    example: "His mother was Italian, hence his name - Luca.",
    vietnameseExample: "Mẹ anh ấy là người Ý, do đó anh ấy có tên là Luca.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_429",
    word: "Hierarchy",
    ipa: "/ˈhaɪə.rɑː.ki/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A system in which people or things are arranged according to their importance.",
    vietnameseDefinition: "Hệ thống cấp bậc",
    collocations: ["social hierarchy", "corporate hierarchy", "strict hierarchy"],
    example: "Some monkeys have a very complex social hierarchy.",
    vietnameseExample: "Một số loài khỉ có một hệ thống cấp bậc xã hội rất phức tạp.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_430",
    word: "Highlight",
    ipa: "/ˈhaɪ.laɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To attract attention to or emphasize something important.",
    vietnameseDefinition: "Làm nổi bật, điểm nhấn",
    collocations: ["highlight the importance", "highlight the need", "highlight a problem"],
    example: "The report highlights the need for improved safety.",
    vietnameseExample: "Báo cáo làm nổi bật nhu cầu cải thiện an toàn.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_431",
    word: "Hypothesis",
    ipa: "/haɪˈpɒθ.ə.sɪs/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An idea or explanation for something that is based on known facts but has not yet been proved.",
    vietnameseDefinition: "Giả thuyết",
    collocations: ["test a hypothesis", "support a hypothesis", "working hypothesis"],
    example: "Several hypotheses for global warming have been suggested.",
    vietnameseExample: "Một số giả thuyết về sự nóng lên toàn cầu đã được đề xuất.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_432",
    word: "Identical",
    ipa: "/aɪˈden.tɪ.kəl/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Exactly the same, or very similar.",
    vietnameseDefinition: "Giống hệt nhau",
    collocations: ["almost identical", "identical twins", "identical to"],
    example: "The two rooms were virtually identical.",
    vietnameseExample: "Hai căn phòng gần như giống hệt nhau.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_433",
    word: "Identify",
    ipa: "/aɪˈden.tɪ.faɪ/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To recognize someone or something and say or prove who or what that person or thing is.",
    vietnameseDefinition: "Nhận dạng, xác định",
    collocations: ["identify a problem", "clearly identify", "identify with"],
    example: "Even the smallest baby can identify its mother by her voice.",
    vietnameseExample: "Ngay cả đứa trẻ nhỏ nhất cũng có thể nhận ra mẹ mình qua giọng nói.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_434",
    word: "Ideology",
    ipa: "/ˌaɪ.diˈɒl.ə.dʒi/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A set of beliefs or principles, especially one on which a political system, party, or organization is based.",
    vietnameseDefinition: "Hệ tư tưởng",
    collocations: ["political ideology", "capitalist ideology", "dominant ideology"],
    example: "The people are caught between two opposing ideologies.",
    vietnameseExample: "Người dân bị kẹt giữa hai hệ tư tưởng đối lập.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_435",
    word: "Ignorance",
    ipa: "/ˈɪɡ.nər.əns/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Lack of knowledge, understanding, or information about something.",
    vietnameseDefinition: "Sự thiếu hiểu biết",
    collocations: ["complete ignorance", "display ignorance", "ignorance of the law"],
    example: "Public ignorance about the disease is still a cause for concern.",
    vietnameseExample: "Sự thiếu hiểu biết của công chúng về căn bệnh này vẫn là một nguyên nhân gây lo ngại.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_436",
    word: "Illustrate",
    ipa: "/ˈɪl.ə.streɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To draw pictures for a book, magazine, etc., or to show the meaning or truth of something more clearly.",
    vietnameseDefinition: "Minh họa",
    collocations: ["clearly illustrate", "illustrate a point", "beautifully illustrated"],
    example: "The lecturer illustrated his point with a diagram on the blackboard.",
    vietnameseExample: "Giảng viên đã minh họa quan điểm của mình bằng một sơ đồ trên bảng đen.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_437",
    word: "Image",
    ipa: "/ˈɪm.ɪdʒ/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A picture in your mind or an idea of how someone or something is.",
    vietnameseDefinition: "Hình ảnh",
    collocations: ["public image", "positive image", "create an image"],
    example: "The company has to work hard to improve its image.",
    vietnameseExample: "Công ty phải làm việc chăm chỉ để cải thiện hình ảnh của mình.",
    level: "B1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_438",
    word: "Impact",
    ipa: "/ˈɪm.pækt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "A powerful effect that something, especially something new, has on a situation or person.",
    vietnameseDefinition: "Tác động, ảnh hưởng",
    collocations: ["major impact", "significant impact", "environmental impact"],
    example: "The anti-smoking campaign had had/made quite an impact on young people.",
    vietnameseExample: "Chiến dịch chống hút thuốc đã có tác động khá lớn đến giới trẻ.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_439",
    word: "Implement",
    ipa: "/ˈɪm.plɪ.ment/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To start using a plan or system.",
    vietnameseDefinition: "Thực hiện, thi hành",
    collocations: ["implement a policy", "implement a plan", "fully implement"],
    example: "The changes to the national health system will be implemented next year.",
    vietnameseExample: "Những thay đổi đối với hệ thống y tế quốc gia sẽ được thực hiện vào năm tới.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_440",
    word: "Implicate",
    ipa: "/ˈɪm.plɪ.keɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To show that someone is involved in a crime or partly responsible for something bad that has happened.",
    vietnameseDefinition: "Lôi kéo vào, ngụ ý",
    collocations: ["be implicated in", "deeply implicated"],
    example: "Have they any evidence to implicate him in the robbery?",
    vietnameseExample: "Họ có bằng chứng nào để lôi kéo anh ta vào vụ cướp không?",
    level: "C2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_441",
    word: "Implicit",
    ipa: "/ɪmˈplɪs.ɪt/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Suggested but not communicated directly.",
    vietnameseDefinition: "Ngầm, ẩn ý",
    collocations: ["implicit assumption", "implicit agreement", "implicit trust"],
    example: "He interpreted her comments as an implicit criticism of the government.",
    vietnameseExample: "Ông giải thích những bình luận của bà như một lời chỉ trích ngầm đối với chính phủ.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_442",
    word: "Imply",
    ipa: "/ɪmˈplaɪ/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To communicate an idea or feeling without saying it directly.",
    vietnameseDefinition: "Ngụ ý, ám chỉ",
    collocations: ["strongly imply", "seem to imply", "imply that"],
    example: "Are you implying (that) I'm fat?",
    vietnameseExample: "Bạn đang ám chỉ (rằng) tôi béo à?",
    level: "B2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_443",
    word: "Impose",
    ipa: "/ɪmˈpəʊz/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To officially force a rule, tax, punishment, etc. to be obeyed or received.",
    vietnameseDefinition: "Áp đặt, đánh (thuế)",
    collocations: ["impose a ban", "impose a fine", "impose restrictions"],
    example: "Very high taxes have recently been imposed on cigarettes.",
    vietnameseExample: "Thuế rất cao gần đây đã được áp dụng đối với thuốc lá.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_444",
    word: "Incentive",
    ipa: "/ɪnˈsen.tɪv/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Something that encourages a person to do something.",
    vietnameseDefinition: "Khuyến khích, động cơ",
    collocations: ["financial incentive", "provide an incentive", "strong incentive"],
    example: "Tax incentives have been very effective in encouraging people to save and invest more of their income.",
    vietnameseExample: "Các ưu đãi thuế đã rất hiệu quả trong việc khuyến khích mọi người tiết kiệm và đầu tư nhiều hơn thu nhập của họ.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_445",
    word: "Incidence",
    ipa: "/ˈɪn.sɪ.dəns/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "An event, or the rate at which something happens.",
    vietnameseDefinition: "Tỷ lệ mắc phải, sự xảy ra",
    collocations: ["high incidence", "incidence of disease", "reduce the incidence"],
    example: "There have been quite a few incidences of bullying in the school this year.",
    vietnameseExample: "Đã có khá nhiều vụ bắt nạt trong trường năm nay.",
    level: "C1",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_446",
    word: "Incline",
    ipa: "/ɪnˈklaɪn/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "To (make someone) feel something or want to do something.",
    vietnameseDefinition: "Có khuynh hướng, nghiêng về",
    collocations: ["incline to think", "incline towards", "steep incline"],
    example: "I incline to the view that peace can be achieved.",
    vietnameseExample: "Tôi nghiêng về quan điểm rằng hòa bình có thể đạt được.",
    level: "C2",
    band: 7,
    topicId: "7-1"
  },
  {
    id: "w_b7_447",
    word: "Income",
    ipa: "/ˈɪn.kʌm/",
    image: "/placeholder.svg?height=400&width=400",
    definition: "Money that is earned from doing work or received from investments.",
    vietnameseDefinition: "Thu nhập",
    collocations: ["low income", "high income", "source of income"],
    example: "More help is needed for people on low incomes.",
    vietnameseExample: "Cần có nhiều sự giúp đỡ hơn cho những người có thu nhập thấp.",
    level: "B2",
    band: 7,
    topicId: "7-1"
  }
];

const content = fs.readFileSync('./src/data/roadmap_vocab.ts', 'utf-8');
const arrayEnd = content.lastIndexOf(']');

let newContent = content.substring(0, arrayEnd);
if (!newContent.trim().endsWith(',')) {
    newContent += ',\n';
}

const entries = newWords.map(item => {
  return `  {
    id: "${item.id}",
    word: ${JSON.stringify(item.word)},
    ipa: ${JSON.stringify(item.ipa)},
    image: ${JSON.stringify(item.image)},
    definition: ${JSON.stringify(item.definition)},
    vietnameseDefinition: ${JSON.stringify(item.vietnameseDefinition)},
    collocations: ${JSON.stringify(item.collocations)},
    example: ${JSON.stringify(item.example)},
    vietnameseExample: ${JSON.stringify(item.vietnameseExample)},
    level: "${item.level}",
    band: ${item.band},
    topicId: "${item.topicId}"
  }`;
});

newContent += entries.join(',\n');
newContent += `\n];\n`;

fs.writeFileSync('./src/data/roadmap_vocab.ts', newContent, 'utf-8');
console.log(`Added ${newWords.length} words.`);
